last_change = 2026-10-09T11:52:01.847129Z
addr = 0x14def0
size = 0x9
name = "CBaseEntity_GetChangeAccessorPathInfo_1"
type = "long long"

[header]
name = "CBaseEntity_GetChangeAccessorPathInfo_1"
addr = 0x14def0
type = "long long"

[header.args]
