last_change = 2026-10-09T11:52:01.847200Z
addr = 0x156d80
size = 0x3
name = "IGameSystem_OnServerPreClientUpdate"

[header]
name = "IGameSystem_OnServerPreClientUpdate"
addr = 0x156d80

[header.args]
