last_change = 2026-10-09T11:52:01.847163Z
addr = 0x156c20
size = 0x3
name = "IGameSystem_OnServerPostAdvanceTick"

[header]
name = "IGameSystem_OnServerPostAdvanceTick"
addr = 0x156c20

[header.args]
