last_change = 2026-10-09T11:52:01.847132Z
addr = 0x153930
size = 0xb
name = "CBaseEntity_FullEdictChanged"
type = "bool"

[header]
name = "CBaseEntity_FullEdictChanged"
addr = 0x153930
type = "bool"

[header.args]
