last_change = 2026-10-09T11:52:01.847293Z
addr = 0x1c77a0
size = 0x742
name = "CCSPlayerPawn_Event_KilledOther"
type = "long long"

[header]
name = "CCSPlayerPawn_Event_KilledOther"
addr = 0x1c77a0
type = "long long"

[header.args]
