last_change = 2026-10-09T11:52:01.847304Z
addr = 0x1da450
size = 0x381
name = "CCSPlayerPawn_OnSwitchWeapons"
type = "void"

[header]
name = "CCSPlayerPawn_OnSwitchWeapons"
addr = 0x1da450
type = "void"

[header.args]
