last_change = 2026-10-09T11:52:01.847336Z
addr = 0x25bad0
size = 0x284
name = "CCSPlayerPawnBase_CheckForIdle"
type = "void"

[header]
name = "CCSPlayerPawnBase_CheckForIdle"
addr = 0x25bad0
type = "void"

[header.args]
