last_change = 2026-10-09T11:52:01.847386Z
addr = 0x299de0
size = 0x8
name = "CGameMoney_GetDataDescMap"
type = "long long *"

[header]
name = "CGameMoney_GetDataDescMap"
addr = 0x299de0
type = "long long *"

[header.args]
