last_change = 2026-10-09T11:52:01.847449Z
addr = 0x2d87f0
size = 0x1d8
name = "CCSBot_PrintIfWatched"
type = "void"

[header]
name = "CCSBot_PrintIfWatched"
addr = 0x2d87f0
type = "void"

[header.args]
