last_change = 2026-10-09T11:52:16.690576Z
addr = 0x2e8cf0
size = 0x384
name = "BotKill_CommandHandler"
type = "void"

[header]
name = "BotKill_CommandHandler"
addr = 0x2e8cf0
type = "void"

[header.args]
