last_change = 2026-10-09T11:52:01.847496Z
addr = 0x342330
size = 0x13be
name = "CInferno_InfernoThink"
type = "long long"

[header]
name = "CInferno_InfernoThink"
addr = 0x342330
type = "long long"

[header.args]
