last_change = 2026-10-09T11:52:01.847505Z
addr = 0x39d700
size = 0x483
name = "CFlashbangProjectile_Detonate"
type = "long long"

[header]
name = "CFlashbangProjectile_Detonate"
addr = 0x39d700
type = "long long"

[header.args]
