last_change = 2026-10-09T11:52:01.847512Z
addr = 0x3cb480
size = 0x1713
name = "CBaseEntity_DrawDebugTextOverlays"
type = "void"

[header]
name = "CBaseEntity_DrawDebugTextOverlays"
addr = 0x3cb480
type = "void"

[header.args]
