last_change = 2026-10-09T11:52:01.847598Z
addr = 0x579520
size = 0xdf
name = "CSpawnGroupMgrGameSystem_CreateLoadingSpawnGroupForSaveFile"
type = "long long"

[header]
name = "CSpawnGroupMgrGameSystem_CreateLoadingSpawnGroupForSaveFile"
addr = 0x579520
type = "long long"

[header.args]
