last_change = 2026-10-09T11:52:18.629602Z
addr = 0x57a6c0
size = 0x827
name = "CPhysicsGameSystem_ProcessContactEvents"
type = "long long"

[header]
name = "CPhysicsGameSystem_ProcessContactEvents"
addr = 0x57a6c0
type = "long long"

[header.args]
