last_change = 2026-10-09T11:52:01.847607Z
addr = 0x59f880
size = 0x1cc
name = "CSpawnGroupMgrGameSystem_DumpSpawnGroups"
type = "void"

[header]
name = "CSpawnGroupMgrGameSystem_DumpSpawnGroups"
addr = 0x59f880
type = "void"

[header.args]
