last_change = 2026-10-09T11:52:01.847636Z
addr = 0x5f9150
size = 0x5f0e
name = "CBaseEntity_GetScriptDescInternal"
type = "long long"

[header]
name = "CBaseEntity_GetScriptDescInternal"
addr = 0x5f9150
type = "long long"

[header.args]
