last_change = 2026-10-09T11:52:01.847638Z
addr = 0x5ff060
size = 0x21a7
name = "CBaseModelEntity_GetScriptDescInternal"
type = "long long"

[header]
name = "CBaseModelEntity_GetScriptDescInternal"
addr = 0x5ff060
type = "long long"

[header.args]
