last_change = 2026-10-09T11:52:01.847678Z
addr = 0x638fe0
size = 0x15
name = "CBaseModelEntity_ScriptGetMaterialGroupHash"

[header]
name = "CBaseModelEntity_ScriptGetMaterialGroupHash"
addr = 0x638fe0

[header.args]
