last_change = 2026-10-09T11:52:01.847714Z
addr = 0x639620
size = 0x33
name = "CBaseModelEntity_ScriptSetMaterialGroup"

[header]
name = "CBaseModelEntity_ScriptSetMaterialGroup"
addr = 0x639620

[header.args]
