last_change = 2026-10-09T11:52:01.847736Z
addr = 0x6397f0
size = 0x32
name = "CBaseEntity_ScriptTransformPointEntityToWorld"

[header]
name = "CBaseEntity_ScriptTransformPointEntityToWorld"
addr = 0x6397f0

[header.args]
