last_change = 2026-10-09T11:52:01.847702Z
addr = 0x639330
size = 0x139
name = "CBaseEntity_ScriptSetAttributeFloatValue"

[header]
name = "CBaseEntity_ScriptSetAttributeFloatValue"
addr = 0x639330

[header.args]
