last_change = 2026-10-09T11:52:01.847644Z
addr = 0x634540
size = 0x50b
name = "CNetworkUtlVectorEmbedded_NetworkStateChanged_m_vecRenderAttributes"
type = "void"

[header]
name = "CNetworkUtlVectorEmbedded_NetworkStateChanged_m_vecRenderAttributes"
addr = 0x634540
type = "void"

[header.args]
