last_change = 2026-10-09T11:52:01.847738Z
addr = 0x639830
size = 0x32
name = "CBaseEntity_ScriptTransformPointWorldToEntity"

[header]
name = "CBaseEntity_ScriptTransformPointWorldToEntity"
addr = 0x639830

[header.args]
