last_change = 2026-10-09T11:52:01.847751Z
addr = 0x91c400
size = 0x439
name = "CCSGameRules_BeginRound"
type = "long long"

[header]
name = "CCSGameRules_BeginRound"
addr = 0x91c400
type = "long long"

[header.args]
