last_change = 2026-10-09T11:52:01.847767Z
addr = 0x94ba30
size = 0x239
name = "CCSGameRules_PlayerSpawn"
type = "long long"

[header]
name = "CCSGameRules_PlayerSpawn"
addr = 0x94ba30
type = "long long"

[header.args]
