last_change = 2026-10-09T11:52:01.847783Z
addr = 0x9af2b0
size = 0x3d7
name = "CSmokeGrenadeProjectile_Create"
type = "long long"

[header]
name = "CSmokeGrenadeProjectile_Create"
addr = 0x9af2b0
type = "long long"

[header.args]
