last_change = 2026-10-09T11:52:22.071240Z
addr = 0x9b04c0
size = 0x208
name = "CSmokeGrenadeProjectile_Detonate"
type = "long long"

[header]
name = "CSmokeGrenadeProjectile_Detonate"
addr = 0x9b04c0
type = "long long"

[header.args]
