last_change = 2026-10-09T11:52:01.847796Z
addr = 0xa07b30
size = 0xb9
name = "CCSWeaponBase_ItemPostFrame_ProcessReloadAction"
type = "long long"

[header]
name = "CCSWeaponBase_ItemPostFrame_ProcessReloadAction"
addr = 0xa07b30
type = "long long"

[header.args]
