last_change = 2026-10-09T11:52:01.847806Z
addr = 0xa63f00
size = 0x218
name = "CCSPlayer_BulletServices_ctor"
type = "long long"

[header]
name = "CCSPlayer_BulletServices_ctor"
addr = 0xa63f00
type = "long long"

[header.args]
