last_change = 2026-10-09T11:52:01.847824Z
addr = 0xa7fae0
size = 0xc
name = "CCSPlayerController_InventoryUpdateThink"
type = "long long"

[header]
name = "CCSPlayerController_InventoryUpdateThink"
addr = 0xa7fae0
type = "long long"

[header.args]
