last_change = 2026-10-09T11:52:01.847844Z
addr = 0xa94330
size = 0x26e
name = "CCSPlayerController_SwitchTeam"
type = "long long"

[header]
name = "CCSPlayerController_SwitchTeam"
addr = 0xa94330
type = "long long"

[header.args]
