last_change = 2026-10-09T11:52:01.847877Z
addr = 0xabb040
size = 0x11ba
name = "FindUseEntity"
type = "unsigned long long *"

[header]
name = "FindUseEntity"
addr = 0xabb040
type = "unsigned long long *"

[header.args]
