last_change = 2026-10-09T11:52:01.847867Z
addr = 0xab4820
size = 0x20a
name = "CCSPlayer_MovementServices_CheckMovingGround"
type = "long long"

[header]
name = "CCSPlayer_MovementServices_CheckMovingGround"
addr = 0xab4820
type = "long long"

[header.args]
