last_change = 2026-10-09T11:52:01.847860Z
addr = 0xab2cf0
size = 0x66f
name = "CCSPlayer_MovementServices_CategorizePosition"
type = "long long"

[header]
name = "CCSPlayer_MovementServices_CategorizePosition"
addr = 0xab2cf0
type = "long long"

[header.args]
