last_change = 2026-10-09T11:52:01.847915Z
addr = 0xade180
size = 0x782
name = "CCSPlayer_MovementServices_OnJumpModern"
type = "void"

[header]
name = "CCSPlayer_MovementServices_OnJumpModern"
addr = 0xade180
type = "void"

[header.args]
