last_change = 2026-10-09T11:52:01.847888Z
addr = 0xad2d40
size = 0x2e
name = "CCSPlayerPawn_OnTakeDamage_Alive"
type = "long long"

[header]
name = "CCSPlayerPawn_OnTakeDamage_Alive"
addr = 0xad2d40
type = "long long"

[header.args]
