last_change = 2026-10-09T11:52:24.389035Z
addr = 0xb13d60
size = 0xa2b
name = "CCSPlayer_WeaponServices_PickupItem"
type = "long long"

[header]
name = "CCSPlayer_WeaponServices_PickupItem"
addr = 0xb13d60
type = "long long"

[header.args]
