last_change = 2026-10-09T11:52:01.847949Z
addr = 0xb43970
size = 0xc1
name = "CBaseModelEntity_DamageDecal"
type = "unsigned long long *"

[header]
name = "CBaseModelEntity_DamageDecal"
addr = 0xb43970
type = "unsigned long long *"

[header.args]
