last_change = 2026-10-09T11:52:01.847974Z
addr = 0xb4cae0
size = 0x5f
name = "CBasePlayerController_GetPawn"
type = "long long"

[header]
name = "CBasePlayerController_GetPawn"
addr = 0xb4cae0
type = "long long"

[header.args]
