last_change = 2026-10-09T11:52:01.848013Z
addr = 0xb6b5f0
size = 0x6b
name = "CBaseModelEntity_ScriptGetAttachmentAngles"

[header]
name = "CBaseModelEntity_ScriptGetAttachmentAngles"
addr = 0xb6b5f0

[header.args]
