last_change = 2026-10-09T11:52:01.848016Z
addr = 0xb6b660
size = 0x47
name = "CBaseModelEntity_ScriptGetAttachmentForward"

[header]
name = "CBaseModelEntity_ScriptGetAttachmentForward"
addr = 0xb6b660

[header.args]
