last_change = 2026-10-09T11:52:26.177243Z
addr = 0xb70a40
size = 0x363
name = "CBasePlayerController_Spawn"
type = "long long"

[header]
name = "CBasePlayerController_Spawn"
addr = 0xb70a40
type = "long long"

[header.args]
