last_change = 2026-10-09T11:52:01.848071Z
addr = 0xbc2950
size = 0x2e4
name = "CEntitySaveRestoreBlockHandler_WriteSaveHeaders"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_WriteSaveHeaders"
addr = 0xbc2950
type = "long long"

[header.args]
