last_change = 2026-10-09T11:52:26.370955Z
addr = 0xbc2680
size = 0x17d
name = "CEntitySaveRestoreBlockHandler_PreSave"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_PreSave"
addr = 0xbc2680
type = "long long"

[header.args]
