last_change = 2026-10-09T11:52:01.848074Z
addr = 0xbc2c50
size = 0x22f
name = "CEntitySaveRestoreBlockHandler_ReadRestoreHeaders"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_ReadRestoreHeaders"
addr = 0xbc2c50
type = "long long"

[header.args]
