last_change = 2026-10-09T11:52:26.950800Z
addr = 0xbe3aa0
size = 0x154
name = "CGameEntitySystem_BuildResourceManifest_ManifestNameOrGroupName"
type = "long long"

[header]
name = "CGameEntitySystem_BuildResourceManifest_ManifestNameOrGroupName"
addr = 0xbe3aa0
type = "long long"

[header.args]
