last_change = 2026-10-09T11:52:01.848114Z
addr = 0xbf2240
size = 0x417
name = "CGameEntitySystem_CheckGlobalState"
type = "void"

[header]
name = "CGameEntitySystem_CheckGlobalState"
addr = 0xbf2240
type = "void"

[header.args]
