last_change = 2026-10-09T11:52:01.848118Z
addr = 0xbf3eb0
size = 0x25
name = "CGameEntitySystem_FindEntityByClassName"
type = "long long"

[header]
name = "CGameEntitySystem_FindEntityByClassName"
addr = 0xbf3eb0
type = "long long"

[header.args]
