last_change = 2026-10-09T11:52:01.848122Z
addr = 0xbf43e0
size = 0xe4
name = "CGameEntitySystem_FindEntityByName"
type = "long long"

[header]
name = "CGameEntitySystem_FindEntityByName"
addr = 0xbf43e0
type = "long long"

[header.args]
