last_change = 2026-10-09T11:52:01.848135Z
addr = 0xc07370
size = 0x5a2
name = "CGameEventManager_LoadEventsFromFile"
type = "void"

[header]
name = "CGameEventManager_LoadEventsFromFile"
addr = 0xc07370
type = "void"

[header.args]
