last_change = 2026-10-09T11:52:01.848152Z
addr = 0xc13510
size = 0x1df
name = "CGameEventManager_RemoveListener"
type = "void"

[header]
name = "CGameEventManager_RemoveListener"
addr = 0xc13510
type = "void"

[header.args]
