last_change = 2026-10-09T11:52:28.303688Z
addr = 0xc241c0
size = 0x3a2
name = "CSource2EntitySystem_StaticInit"
type = "char"

[header]
name = "CSource2EntitySystem_StaticInit"
addr = 0xc241c0
type = "char"

[header.args]
