last_change = 2026-10-09T11:52:28.785795Z
addr = 0xc36680
size = 0x68
name = "CLoopModeFactory_CLoopModeGame_Shutdown"
type = "long long"

[header]
name = "CLoopModeFactory_CLoopModeGame_Shutdown"
addr = 0xc36680
type = "long long"

[header.args]
