last_change = 2026-10-09T11:52:01.848214Z
addr = 0xc52ac0
size = 0x162
name = "CLoopModeGame_ShutdownServer"
type = "void"

[header]
name = "CLoopModeGame_ShutdownServer"
addr = 0xc52ac0
type = "void"

[header.args]
