last_change = 2026-10-09T11:52:01.848217Z
addr = 0xc54d50
size = 0xd0
name = "CLoopModeGame_OnFrameBoundary"
type = "long long"

[header]
name = "CLoopModeGame_OnFrameBoundary"
addr = 0xc54d50
type = "long long"

[header.args]
