last_change = 2026-10-09T11:52:30.482900Z
addr = 0xcd45a0
size = 0x84d
name = "CBaseEntity_ctor"
type = "long long"

[header]
name = "CBaseEntity_ctor"
addr = 0xcd45a0
type = "long long"

[header.args]
