last_change = 2026-10-09T11:52:01.848311Z
addr = 0xcd9be0
size = 0x3a
name = "CCSPlayerController_AddedToEntityDatabase"
type = "long long"

[header]
name = "CCSPlayerController_AddedToEntityDatabase"
addr = 0xcd9be0
type = "long long"

[header.args]
