last_change = 2026-10-09T11:52:30.870079Z
addr = 0xcdd240
size = 0x121
name = "FireTarget_CommandHandler"
type = "void"

[header]
name = "FireTarget_CommandHandler"
addr = 0xcdd240
type = "void"

[header.args]
