last_change = 2026-10-09T11:52:01.848309Z
addr = 0xcd8ab0
size = 0xe0
name = "CBaseEntity_AddContextForScriptNumeric"

[header]
name = "CBaseEntity_AddContextForScriptNumeric"
addr = 0xcd8ab0

[header.args]
