last_change = 2026-10-09T11:52:30.920338Z
addr = 0xce8bb0
size = 0x17
name = "CBasePlayerPawn_DropActivePlayerWeapon"
type = "long long"

[header]
name = "CBasePlayerPawn_DropActivePlayerWeapon"
addr = 0xce8bb0
type = "long long"

[header.args]
