last_change = 2026-10-09T11:52:01.848354Z
addr = 0xd042f0
size = 0x3b
name = "CBaseEntity_ScriptGetLocalAngularVelocity_OBSOLETE"

[header]
name = "CBaseEntity_ScriptGetLocalAngularVelocity_OBSOLETE"
addr = 0xd042f0

[header.args]
