last_change = 2026-10-09T11:52:01.848409Z
addr = 0xd11620
size = 0x5d8
name = "CMomentaryRotButton_Use"
type = "double"

[header]
name = "CMomentaryRotButton_Use"
addr = 0xd11620
type = "double"

[header.args]
