last_change = 2026-10-09T11:52:01.848413Z
addr = 0xd12040
size = 0x1af
name = "CBaseEntity_VPhysicsCollision"
type = "long long"

[header]
name = "CBaseEntity_VPhysicsCollision"
addr = 0xd12040
type = "long long"

[header.args]
