last_change = 2026-10-09T11:52:01.848415Z
addr = 0xd4ea30
size = 0x22
name = "CEnvEntityIgniter_Precache"
type = "long long"

[header]
name = "CEnvEntityIgniter_Precache"
addr = 0xd4ea30
type = "long long"

[header.args]
