last_change = 2026-10-09T11:52:01.848437Z
addr = 0xdd0300
size = 0x78
name = "CSource2Server_GameCreateNetworkStringTables"
type = "long long"

[header]
name = "CSource2Server_GameCreateNetworkStringTables"
addr = 0xdd0300
type = "long long"

[header.args]
