last_change = 2026-10-09T11:52:01.848500Z
addr = 0xddcdc0
size = 0x323
name = "CSource2GameClients_ClientDisconnect"
type = "long long"

[header]
name = "CSource2GameClients_ClientDisconnect"
addr = 0xddcdc0
type = "long long"

[header.args]
