last_change = 2026-10-09T11:52:01.848512Z
addr = 0xdddb70
size = 0xa
name = "CSource2GameClients_ClientSetConVarUserInfoSet"
type = "long long"

[header]
name = "CSource2GameClients_ClientSetConVarUserInfoSet"
addr = 0xdddb70
type = "long long"

[header.args]
