last_change = 2026-10-09T11:52:01.848433Z
addr = 0xdd0120
size = 0x11c
name = "CSource2Server_Shutdown"
type = "long long"

[header]
name = "CSource2Server_Shutdown"
addr = 0xdd0120
type = "long long"

[header.args]
