last_change = 2026-10-09T11:52:01.848442Z
addr = 0xdd0480
size = 0xde
name = "CSource2Server_PreWorldUpdate"
type = "long long"

[header]
name = "CSource2Server_PreWorldUpdate"
addr = 0xdd0480
type = "long long"

[header.args]
