last_change = 2026-10-09T11:52:01.848449Z
addr = 0xdd0d00
size = 0x19
name = "CSource2Server_ShouldTimeoutClient"
type = "char"

[header]
name = "CSource2Server_ShouldTimeoutClient"
addr = 0xdd0d00
type = "char"

[header.args]
