last_change = 2026-10-09T11:52:01.848524Z
addr = 0xde6bf0
size = 0x3a2
name = "CSource2GameClients_OnClientConnected"
type = "long long"

[header]
name = "CSource2GameClients_OnClientConnected"
addr = 0xde6bf0
type = "long long"

[header.args]
