last_change = 2026-10-09T11:52:01.848530Z
addr = 0xde99b0
size = 0x1e3
name = "CSource2GameClients_SendHLTVStatusMessage"
type = "long long"

[header]
name = "CSource2GameClients_SendHLTVStatusMessage"
addr = 0xde99b0
type = "long long"

[header.args]
