last_change = 2026-10-09T11:52:01.848551Z
addr = 0xe67880
size = 0x71
name = "CMultiplayRules_ClientDisconnected"
type = "long long"

[header]
name = "CMultiplayRules_ClientDisconnected"
addr = 0xe67880
type = "long long"

[header.args]
