last_change = 2026-10-09T11:52:01.848561Z
addr = 0xe884d0
size = 0x34
name = "CBaseEntity_PhysicsTouch"
type = "long long"

[header]
name = "CBaseEntity_PhysicsTouch"
addr = 0xe884d0
type = "long long"

[header.args]
