last_change = 2026-10-09T11:52:01.848556Z
addr = 0xe859f0
size = 0x16e
name = "PhysCollisionDust"
type = "float *"

[header]
name = "PhysCollisionDust"
addr = 0xe859f0
type = "float *"

[header.args]
