last_change = 2026-10-09T11:52:35.606279Z
addr = 0xe96090
size = 0xf6
name = "CBaseEntity_VPhysicsStartTouch"
type = "long long"

[header]
name = "CBaseEntity_VPhysicsStartTouch"
addr = 0xe96090
type = "long long"

[header.args]
