last_change = 2026-10-09T11:52:01.848579Z
addr = 0xeb8040
size = 0x1e3
name = "CPlayerCommandQueue_ctor"
type = "long long"

[header]
name = "CPlayerCommandQueue_ctor"
addr = 0xeb8040
type = "long long"

[header.args]
