last_change = 2026-10-09T11:52:35.804594Z
addr = 0xebc2e0
size = 0x5ea
name = "CPointTeleportAPI_TeleportEntityInternal"
type = "long long"

[header]
name = "CPointTeleportAPI_TeleportEntityInternal"
addr = 0xebc2e0
type = "long long"

[header.args]
