last_change = 2026-10-09T11:52:01.848575Z
addr = 0xeb66c0
size = 0x1d0
name = "CPointTeleport_Activate"
type = "long long"

[header]
name = "CPointTeleport_Activate"
addr = 0xeb66c0
type = "long long"

[header.args]
