last_change = 2026-10-09T11:52:01.848604Z
addr = 0xf611d0
size = 0x1a3
name = "CBaseEntity_EmitSound"
type = "long long"

[header]
name = "CBaseEntity_EmitSound"
addr = 0xf611d0
type = "long long"

[header.args]
