last_change = 2026-10-09T11:52:01.848626Z
addr = 0xfe18f0
size = 0x9e
name = "UTIL_ClientPrintAll"
type = "long long"

[header]
name = "UTIL_ClientPrintAll"
addr = 0xfe18f0
type = "long long"

[header.args]
