last_change = 2026-10-09T11:52:01.848669Z
addr = 0x1377410
size = 0x7e
name = "CEntitySystem_CreateEntitySystem"
type = "long long"

[header]
name = "CEntitySystem_CreateEntitySystem"
addr = 0x1377410
type = "long long"

[header.args]
