last_change = 2026-10-09T11:52:37.999614Z
addr = 0x137cd40
size = 0x2c
name = "CEntitySystem_ForceSetInPVSCallsIntoQueue"
type = "long long"

[header]
name = "CEntitySystem_ForceSetInPVSCallsIntoQueue"
addr = 0x137cd40
type = "long long"

[header.args]
