last_change = 2026-10-09T11:52:37.522684Z
addr = 0x1378b10
size = 0x1b5
name = "CEntitySystem_DestroyEntityImmediate"
type = "void"

[header]
name = "CEntitySystem_DestroyEntityImmediate"
addr = 0x1378b10
type = "void"

[header.args]
