last_change = 2026-10-09T11:52:01.848664Z
addr = 0x1377060
size = 0x27b
name = "CEntitySystem_CreateEntity"
type = "long long"

[header]
name = "CEntitySystem_CreateEntity"
addr = 0x1377060
type = "long long"

[header.args]
