last_change = 2026-10-09T11:52:38.568425Z
addr = 0x1381b30
size = 0x7f
name = "CEntitySystem_PostDataUpdate"
type = "long long"

[header]
name = "CEntitySystem_PostDataUpdate"
addr = 0x1381b30
type = "long long"

[header.args]
