last_change = 2026-10-09T11:52:01.848757Z
addr = 0x138a300
size = 0x38a
name = "CEntityIOOutput_FireOutputInternal"
type = "long long"

[header]
name = "CEntityIOOutput_FireOutputInternal"
addr = 0x138a300
type = "long long"

[header.args]
