last_change = 2026-10-09T11:52:01.848767Z
addr = 0x138cec0
size = 0x18b
name = "CEntityKeyValues_LoadFromContext"
type = "char"

[header]
name = "CEntityKeyValues_LoadFromContext"
addr = 0x138cec0
type = "char"

[header.args]
