last_change = 2026-10-09T11:52:38.239820Z
addr = 0x13804a0
size = 0xc7
name = "CEntitySystem_InstallCreationWrapperCallbacks"
type = "long long"

[header]
name = "CEntitySystem_InstallCreationWrapperCallbacks"
addr = 0x13804a0
type = "long long"

[header.args]
