last_change = 2026-10-09T11:52:01.848725Z
addr = 0x1380570
size = 0x9c
name = "CEntitySystem_InvokePrecacheCallback"
type = "long long"

[header]
name = "CEntitySystem_InvokePrecacheCallback"
addr = 0x1380570
type = "long long"

[header.args]
