last_change = 2026-10-09T11:52:01.848771Z
addr = 0x13a0d90
size = 0xd6
name = "CEntityInstance_AcceptInput"
type = "long long"

[header]
name = "CEntityInstance_AcceptInput"
addr = 0x13a0d90
type = "long long"

[header.args]
