last_change = 2026-10-09T11:52:01.848786Z
addr = 0x13a2870
size = 0x11a
name = "CEntityInstance_Precache"
type = "void"

[header]
name = "CEntityInstance_Precache"
addr = 0x13a2870
type = "void"

[header.args]
