last_change = 2026-10-09T11:52:01.848783Z
addr = 0x13a2400
size = 0x5
name = "CEntityInstance_GetScriptDesc"
type = "long long"

[header]
name = "CEntityInstance_GetScriptDesc"
addr = 0x13a2400
type = "long long"

[header.args]
